### ISSUE TITLE
doesn't seem to take context into account

### ISSUE THREAD

**Issue by brendanjerwin** [landaire/deoplete-swift#1]
It seems to get completions from sourcekitten, but I suspect that the position offset (or maybe the input file?) isn't right. 

![cursor_and_default](https://cloud.githubusercontent.com/assets/3039/14491867/55ac41da-0149-11e6-85f6-423be93c73db.png)

**Comment by landaire** [comment]
You know, that's something I suspected as well and I'm not sure why it happens. The foundation for this code was taken from https://github.com/landaire/deoplete-d which works just fine. I did some testing before with sourcekitten and the same file/position via the CLI and still couldn't get it to work if I remember correctly. I'll do some more testing and get back to you though.

**Comment by brendanjerwin** [comment]
I found this guy: https://github.com/mitsuse/autocomplete-swift/tree/master it seems to have a lot of it figured out, but for the wrong completion engine!

**Comment by brendanjerwin** [comment]
I notice he plans to support neovim... I wonder if there might be an opportunity to merge approaches? (peanut gallery here, I know.)

**Comment by landaire** [comment]
With regards to the autocomplete-swift project, I'll see if I can improve this a bit. I know I said I'd fix this issue a couple weeks ago, things came up, life happens, etc. I'm updating the README right now to add some TODO items.
